/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "/home/sjana/ASN-Defns/e2ap-oran-wg3-v01.00.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_CauseRIC_H_
#define	_CauseRIC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CauseRIC {
	CauseRIC_ran_function_id_Invalid	= 0,
	CauseRIC_action_not_supported	= 1,
	CauseRIC_excessive_actions	= 2,
	CauseRIC_duplicate_action	= 3,
	CauseRIC_duplicate_event	= 4,
	CauseRIC_function_resource_limit	= 5,
	CauseRIC_request_id_unknown	= 6,
	CauseRIC_inconsistent_action_subsequent_action_sequence	= 7,
	CauseRIC_control_message_invalid	= 8,
	CauseRIC_call_process_id_invalid	= 9,
	CauseRIC_unspecified	= 10
	/*
	 * Enumeration is extensible
	 */
} e_CauseRIC;

/* CauseRIC */
typedef long	 CauseRIC_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CauseRIC_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CauseRIC;
extern const asn_INTEGER_specifics_t asn_SPC_CauseRIC_specs_1;
asn_struct_free_f CauseRIC_free;
asn_struct_print_f CauseRIC_print;
asn_constr_check_f CauseRIC_constraint;
ber_type_decoder_f CauseRIC_decode_ber;
der_type_encoder_f CauseRIC_encode_der;
xer_type_decoder_f CauseRIC_decode_xer;
xer_type_encoder_f CauseRIC_encode_xer;
per_type_decoder_f CauseRIC_decode_uper;
per_type_encoder_f CauseRIC_encode_uper;
per_type_decoder_f CauseRIC_decode_aper;
per_type_encoder_f CauseRIC_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CauseRIC_H_ */
#include <asn_internal.h>
