/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_CellResourceReportListItem_H_
#define	_CellResourceReportListItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NRCGI.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ServedPlmnPerCellListItem;

/* CellResourceReportListItem */
typedef struct CellResourceReportListItem {
	NRCGI_t	 nRCGI;
	long	*dl_TotalofAvailablePRBs;	/* OPTIONAL */
	long	*ul_TotalofAvailablePRBs;	/* OPTIONAL */
	struct CellResourceReportListItem__servedPlmnPerCellList {
		A_SEQUENCE_OF(struct ServedPlmnPerCellListItem) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} servedPlmnPerCellList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellResourceReportListItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellResourceReportListItem;
extern asn_SEQUENCE_specifics_t asn_SPC_CellResourceReportListItem_specs_1;
extern asn_TYPE_member_t asn_MBR_CellResourceReportListItem_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _CellResourceReportListItem_H_ */
#include <asn_internal.h>
