/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_E2SM_KPM_IndicationMessage_H_
#define	_E2SM_KPM_IndicationMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2SM_KPM_IndicationMessage_PR {
	E2SM_KPM_IndicationMessage_PR_NOTHING,	/* No components present */
	E2SM_KPM_IndicationMessage_PR_indicationMessage_Format1
	/* Extensions may appear below */
	
} E2SM_KPM_IndicationMessage_PR;

/* Forward declarations */
struct E2SM_KPM_IndicationMessage_Format1;

/* E2SM-KPM-IndicationMessage */
typedef struct E2SM_KPM_IndicationMessage {
	E2SM_KPM_IndicationMessage_PR present;
	union E2SM_KPM_IndicationMessage_u {
		struct E2SM_KPM_IndicationMessage_Format1	*indicationMessage_Format1;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPM_IndicationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPM_IndicationMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPM_IndicationMessage_H_ */
#include <asn_internal.h>
