/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_E2SM_RC_ControlHeader_Format1_H_
#define	_E2SM_RC_ControlHeader_Format1_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-Identity.h"
#include "RIC-Style-Type.h"
#include "RIC-ControlAction-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM-RC-ControlHeader-Format1 */
typedef struct E2SM_RC_ControlHeader_Format1 {
	UE_Identity_t	 ueId;
	RIC_Style_Type_t	 ric_ControlStyle_Type;
	RIC_ControlAction_ID_t	 ric_ControlAction_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_ControlHeader_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_ControlHeader_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_ControlHeader_Format1_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_ControlHeader_Format1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_ControlHeader_Format1_H_ */
#include <asn_internal.h>
