/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_MeasurementTypeName_H_
#define	_MeasurementTypeName_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MeasurementTypeName */
typedef PrintableString_t	 MeasurementTypeName_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_MeasurementTypeName_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_MeasurementTypeName;
asn_struct_free_f MeasurementTypeName_free;
asn_struct_print_f MeasurementTypeName_print;
asn_constr_check_f MeasurementTypeName_constraint;
ber_type_decoder_f MeasurementTypeName_decode_ber;
der_type_encoder_f MeasurementTypeName_encode_der;
xer_type_decoder_f MeasurementTypeName_decode_xer;
xer_type_encoder_f MeasurementTypeName_encode_xer;
oer_type_decoder_f MeasurementTypeName_decode_oer;
oer_type_encoder_f MeasurementTypeName_encode_oer;
per_type_decoder_f MeasurementTypeName_decode_uper;
per_type_encoder_f MeasurementTypeName_encode_uper;
per_type_decoder_f MeasurementTypeName_decode_aper;
per_type_encoder_f MeasurementTypeName_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MeasurementTypeName_H_ */
#include <asn_internal.h>
