/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_PerUE_PM_Item_H_
#define	_PerUE_PM_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-Identity.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PM_Info_Item;

/* PerUE-PM-Item */
typedef struct PerUE_PM_Item {
	UE_Identity_t	 ueId;
	struct PerUE_PM_Item__list_of_PM_Information {
		A_SEQUENCE_OF(struct PM_Info_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *list_of_PM_Information;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerUE_PM_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerUE_PM_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PerUE_PM_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PerUE_PM_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PerUE_PM_Item_H_ */
#include <asn_internal.h>
