/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "PF-ContainerListItem.h"

asn_TYPE_member_t asn_MBR_PF_ContainerListItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PF_ContainerListItem, interface_type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NI_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"interface-type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PF_ContainerListItem, o_CU_UP_PM_Container),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CUUPMeasurement_Container,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"o-CU-UP-PM-Container"
		},
};
static const ber_tlv_tag_t asn_DEF_PF_ContainerListItem_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PF_ContainerListItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* interface-type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* o-CU-UP-PM-Container */
};
asn_SEQUENCE_specifics_t asn_SPC_PF_ContainerListItem_specs_1 = {
	sizeof(struct PF_ContainerListItem),
	offsetof(struct PF_ContainerListItem, _asn_ctx),
	asn_MAP_PF_ContainerListItem_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PF_ContainerListItem = {
	"PF-ContainerListItem",
	"PF-ContainerListItem",
	&asn_OP_SEQUENCE,
	asn_DEF_PF_ContainerListItem_tags_1,
	sizeof(asn_DEF_PF_ContainerListItem_tags_1)
		/sizeof(asn_DEF_PF_ContainerListItem_tags_1[0]), /* 1 */
	asn_DEF_PF_ContainerListItem_tags_1,	/* Same as above */
	sizeof(asn_DEF_PF_ContainerListItem_tags_1)
		/sizeof(asn_DEF_PF_ContainerListItem_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PF_ContainerListItem_1,
	2,	/* Elements count */
	&asn_SPC_PF_ContainerListItem_specs_1	/* Additional specs */
};

