/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-Containers"
 * 	found in "E2AP-Containers-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#include "ProtocolIE-Container.h"

#include "ProtocolIE-Field.h"
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P0_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P1_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P2_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P3_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P4_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P4_constr_9 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P5_constr_11 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P5_constr_11 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P6_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P6_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P7_constr_15 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P7_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P8_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P8_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P9_constr_19 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P9_constr_19 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P10_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P10_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P11_constr_23 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P11_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P12_constr_25 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P12_constr_25 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P13_constr_27 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P13_constr_27 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P14_constr_29 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P14_constr_29 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P15_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P15_constr_31 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P16_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P16_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P17_constr_35 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P17_constr_35 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P18_constr_37 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P18_constr_37 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ProtocolIE_Container_87P19_constr_39 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..65535)) */};
asn_per_constraints_t asn_PER_type_ProtocolIE_Container_87P19_constr_39 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (SIZE(0..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P0_specs_1 = {
	sizeof(struct ProtocolIE_Container_87P0),
	offsetof(struct ProtocolIE_Container_87P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P0 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_Container_87P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_87P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_Container_87P0_tags_1[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P0_constr_1, &asn_PER_type_ProtocolIE_Container_87P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P0_1,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P1_specs_3 = {
	sizeof(struct ProtocolIE_Container_87P1),
	offsetof(struct ProtocolIE_Container_87P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P1 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P1_tags_3,
	sizeof(asn_DEF_ProtocolIE_Container_87P1_tags_3)
		/sizeof(asn_DEF_ProtocolIE_Container_87P1_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P1_tags_3)
		/sizeof(asn_DEF_ProtocolIE_Container_87P1_tags_3[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P1_constr_3, &asn_PER_type_ProtocolIE_Container_87P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P1_3,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P2_specs_5 = {
	sizeof(struct ProtocolIE_Container_87P2),
	offsetof(struct ProtocolIE_Container_87P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P2 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P2_tags_5,
	sizeof(asn_DEF_ProtocolIE_Container_87P2_tags_5)
		/sizeof(asn_DEF_ProtocolIE_Container_87P2_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P2_tags_5)
		/sizeof(asn_DEF_ProtocolIE_Container_87P2_tags_5[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P2_constr_5, &asn_PER_type_ProtocolIE_Container_87P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P2_5,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P3_specs_7 = {
	sizeof(struct ProtocolIE_Container_87P3),
	offsetof(struct ProtocolIE_Container_87P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P3 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P3_tags_7,
	sizeof(asn_DEF_ProtocolIE_Container_87P3_tags_7)
		/sizeof(asn_DEF_ProtocolIE_Container_87P3_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P3_tags_7)
		/sizeof(asn_DEF_ProtocolIE_Container_87P3_tags_7[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P3_constr_7, &asn_PER_type_ProtocolIE_Container_87P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P3_7,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P3_specs_7	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P4_9[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteResponse_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P4_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P4_specs_9 = {
	sizeof(struct ProtocolIE_Container_87P4),
	offsetof(struct ProtocolIE_Container_87P4, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P4 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P4_tags_9,
	sizeof(asn_DEF_ProtocolIE_Container_87P4_tags_9)
		/sizeof(asn_DEF_ProtocolIE_Container_87P4_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P4_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P4_tags_9)
		/sizeof(asn_DEF_ProtocolIE_Container_87P4_tags_9[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P4_constr_9, &asn_PER_type_ProtocolIE_Container_87P4_constr_9, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P4_9,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P4_specs_9	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P5_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICsubscriptionDeleteFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P5_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P5_specs_11 = {
	sizeof(struct ProtocolIE_Container_87P5),
	offsetof(struct ProtocolIE_Container_87P5, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P5 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P5_tags_11,
	sizeof(asn_DEF_ProtocolIE_Container_87P5_tags_11)
		/sizeof(asn_DEF_ProtocolIE_Container_87P5_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P5_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P5_tags_11)
		/sizeof(asn_DEF_ProtocolIE_Container_87P5_tags_11[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P5_constr_11, &asn_PER_type_ProtocolIE_Container_87P5_constr_11, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P5_11,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P5_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P6_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICindication_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P6_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P6_specs_13 = {
	sizeof(struct ProtocolIE_Container_87P6),
	offsetof(struct ProtocolIE_Container_87P6, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P6 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P6_tags_13,
	sizeof(asn_DEF_ProtocolIE_Container_87P6_tags_13)
		/sizeof(asn_DEF_ProtocolIE_Container_87P6_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P6_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P6_tags_13)
		/sizeof(asn_DEF_ProtocolIE_Container_87P6_tags_13[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P6_constr_13, &asn_PER_type_ProtocolIE_Container_87P6_constr_13, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P6_13,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P6_specs_13	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P7_15[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolRequest_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P7_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P7_specs_15 = {
	sizeof(struct ProtocolIE_Container_87P7),
	offsetof(struct ProtocolIE_Container_87P7, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P7 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P7_tags_15,
	sizeof(asn_DEF_ProtocolIE_Container_87P7_tags_15)
		/sizeof(asn_DEF_ProtocolIE_Container_87P7_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P7_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P7_tags_15)
		/sizeof(asn_DEF_ProtocolIE_Container_87P7_tags_15[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P7_constr_15, &asn_PER_type_ProtocolIE_Container_87P7_constr_15, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P7_15,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P7_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P8_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolAcknowledge_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P8_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P8_specs_17 = {
	sizeof(struct ProtocolIE_Container_87P8),
	offsetof(struct ProtocolIE_Container_87P8, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P8 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P8_tags_17,
	sizeof(asn_DEF_ProtocolIE_Container_87P8_tags_17)
		/sizeof(asn_DEF_ProtocolIE_Container_87P8_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P8_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P8_tags_17)
		/sizeof(asn_DEF_ProtocolIE_Container_87P8_tags_17[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P8_constr_17, &asn_PER_type_ProtocolIE_Container_87P8_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P8_17,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P8_specs_17	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P9_19[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICcontrolFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P9_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P9_specs_19 = {
	sizeof(struct ProtocolIE_Container_87P9),
	offsetof(struct ProtocolIE_Container_87P9, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P9 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P9_tags_19,
	sizeof(asn_DEF_ProtocolIE_Container_87P9_tags_19)
		/sizeof(asn_DEF_ProtocolIE_Container_87P9_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P9_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P9_tags_19)
		/sizeof(asn_DEF_ProtocolIE_Container_87P9_tags_19[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P9_constr_19, &asn_PER_type_ProtocolIE_Container_87P9_constr_19, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P9_19,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P9_specs_19	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P10_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ErrorIndication_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P10_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P10_specs_21 = {
	sizeof(struct ProtocolIE_Container_87P10),
	offsetof(struct ProtocolIE_Container_87P10, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P10 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P10_tags_21,
	sizeof(asn_DEF_ProtocolIE_Container_87P10_tags_21)
		/sizeof(asn_DEF_ProtocolIE_Container_87P10_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P10_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P10_tags_21)
		/sizeof(asn_DEF_ProtocolIE_Container_87P10_tags_21[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P10_constr_21, &asn_PER_type_ProtocolIE_Container_87P10_constr_21, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P10_21,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P10_specs_21	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P11_23[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupRequestIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P11_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P11_specs_23 = {
	sizeof(struct ProtocolIE_Container_87P11),
	offsetof(struct ProtocolIE_Container_87P11, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P11 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P11_tags_23,
	sizeof(asn_DEF_ProtocolIE_Container_87P11_tags_23)
		/sizeof(asn_DEF_ProtocolIE_Container_87P11_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P11_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P11_tags_23)
		/sizeof(asn_DEF_ProtocolIE_Container_87P11_tags_23[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P11_constr_23, &asn_PER_type_ProtocolIE_Container_87P11_constr_23, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P11_23,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P11_specs_23	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P12_25[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupResponseIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P12_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P12_specs_25 = {
	sizeof(struct ProtocolIE_Container_87P12),
	offsetof(struct ProtocolIE_Container_87P12, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P12 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P12_tags_25,
	sizeof(asn_DEF_ProtocolIE_Container_87P12_tags_25)
		/sizeof(asn_DEF_ProtocolIE_Container_87P12_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P12_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P12_tags_25)
		/sizeof(asn_DEF_ProtocolIE_Container_87P12_tags_25[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P12_constr_25, &asn_PER_type_ProtocolIE_Container_87P12_constr_25, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P12_25,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P12_specs_25	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P13_27[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2setupFailureIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P13_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P13_specs_27 = {
	sizeof(struct ProtocolIE_Container_87P13),
	offsetof(struct ProtocolIE_Container_87P13, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P13 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P13_tags_27,
	sizeof(asn_DEF_ProtocolIE_Container_87P13_tags_27)
		/sizeof(asn_DEF_ProtocolIE_Container_87P13_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P13_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P13_tags_27)
		/sizeof(asn_DEF_ProtocolIE_Container_87P13_tags_27[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P13_constr_27, &asn_PER_type_ProtocolIE_Container_87P13_constr_27, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P13_27,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P13_specs_27	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P14_29[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetRequestIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P14_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P14_specs_29 = {
	sizeof(struct ProtocolIE_Container_87P14),
	offsetof(struct ProtocolIE_Container_87P14, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P14 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P14_tags_29,
	sizeof(asn_DEF_ProtocolIE_Container_87P14_tags_29)
		/sizeof(asn_DEF_ProtocolIE_Container_87P14_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P14_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P14_tags_29)
		/sizeof(asn_DEF_ProtocolIE_Container_87P14_tags_29[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P14_constr_29, &asn_PER_type_ProtocolIE_Container_87P14_constr_29, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P14_29,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P14_specs_29	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P15_31[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ResetResponseIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P15_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P15_specs_31 = {
	sizeof(struct ProtocolIE_Container_87P15),
	offsetof(struct ProtocolIE_Container_87P15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P15 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P15_tags_31,
	sizeof(asn_DEF_ProtocolIE_Container_87P15_tags_31)
		/sizeof(asn_DEF_ProtocolIE_Container_87P15_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P15_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P15_tags_31)
		/sizeof(asn_DEF_ProtocolIE_Container_87P15_tags_31[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P15_constr_31, &asn_PER_type_ProtocolIE_Container_87P15_constr_31, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P15_31,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P15_specs_31	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P16_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdate_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P16_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P16_specs_33 = {
	sizeof(struct ProtocolIE_Container_87P16),
	offsetof(struct ProtocolIE_Container_87P16, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P16 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P16_tags_33,
	sizeof(asn_DEF_ProtocolIE_Container_87P16_tags_33)
		/sizeof(asn_DEF_ProtocolIE_Container_87P16_tags_33[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P16_tags_33,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P16_tags_33)
		/sizeof(asn_DEF_ProtocolIE_Container_87P16_tags_33[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P16_constr_33, &asn_PER_type_ProtocolIE_Container_87P16_constr_33, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P16_33,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P16_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P17_35[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdateAcknowledge_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P17_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P17_specs_35 = {
	sizeof(struct ProtocolIE_Container_87P17),
	offsetof(struct ProtocolIE_Container_87P17, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P17 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P17_tags_35,
	sizeof(asn_DEF_ProtocolIE_Container_87P17_tags_35)
		/sizeof(asn_DEF_ProtocolIE_Container_87P17_tags_35[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P17_tags_35,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P17_tags_35)
		/sizeof(asn_DEF_ProtocolIE_Container_87P17_tags_35[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P17_constr_35, &asn_PER_type_ProtocolIE_Container_87P17_constr_35, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P17_35,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P17_specs_35	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P18_37[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceUpdateFailure_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P18_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P18_specs_37 = {
	sizeof(struct ProtocolIE_Container_87P18),
	offsetof(struct ProtocolIE_Container_87P18, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P18 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P18_tags_37,
	sizeof(asn_DEF_ProtocolIE_Container_87P18_tags_37)
		/sizeof(asn_DEF_ProtocolIE_Container_87P18_tags_37[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P18_tags_37,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P18_tags_37)
		/sizeof(asn_DEF_ProtocolIE_Container_87P18_tags_37[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P18_constr_37, &asn_PER_type_ProtocolIE_Container_87P18_constr_37, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P18_37,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P18_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProtocolIE_Container_87P19_39[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_RICserviceQuery_IEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ProtocolIE_Container_87P19_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_87P19_specs_39 = {
	sizeof(struct ProtocolIE_Container_87P19),
	offsetof(struct ProtocolIE_Container_87P19, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_87P19 = {
	"ProtocolIE-Container",
	"ProtocolIE-Container",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ProtocolIE_Container_87P19_tags_39,
	sizeof(asn_DEF_ProtocolIE_Container_87P19_tags_39)
		/sizeof(asn_DEF_ProtocolIE_Container_87P19_tags_39[0]), /* 1 */
	asn_DEF_ProtocolIE_Container_87P19_tags_39,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_Container_87P19_tags_39)
		/sizeof(asn_DEF_ProtocolIE_Container_87P19_tags_39[0]), /* 1 */
	{ &asn_OER_type_ProtocolIE_Container_87P19_constr_39, &asn_PER_type_ProtocolIE_Container_87P19_constr_39, SEQUENCE_OF_constraint },
	asn_MBR_ProtocolIE_Container_87P19_39,
	1,	/* Single element */
	&asn_SPC_ProtocolIE_Container_87P19_specs_39	/* Additional specs */
};

