/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-HelloWorld-IEs"
 * 	found in "/home/sjana/ASN-Defns/e2sm-HelloWorld-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_RANparameter_Name_H_
#define	_RANparameter_Name_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANparameter-Name */
typedef OCTET_STRING_t	 RANparameter_Name_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANparameter_Name;
asn_struct_free_f RANparameter_Name_free;
asn_struct_print_f RANparameter_Name_print;
asn_constr_check_f RANparameter_Name_constraint;
ber_type_decoder_f RANparameter_Name_decode_ber;
der_type_encoder_f RANparameter_Name_encode_der;
xer_type_decoder_f RANparameter_Name_decode_xer;
xer_type_encoder_f RANparameter_Name_encode_xer;
per_type_decoder_f RANparameter_Name_decode_uper;
per_type_encoder_f RANparameter_Name_encode_uper;
per_type_decoder_f RANparameter_Name_decode_aper;
per_type_encoder_f RANparameter_Name_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANparameter_Name_H_ */
#include <asn_internal.h>
