/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-HelloWorld-IEs"
 * 	found in "/home/sjana/ASN-Defns/e2sm-HelloWorld-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_RANparameter_Item_H_
#define	_RANparameter_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RANparameter-ID.h"
#include "RANparameter-Name.h"
#include "RANparameter-Test.h"
#include "RANparameter-Value.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RANparameter-Item */
typedef struct RANparameter_Item {
	RANparameter_ID_t	 ranParameter_ID;
	RANparameter_Name_t	 ranParameter_Name;
	RANparameter_Test_t	 ranParameter_Test;
	RANparameter_Value_t	 ranParameter_Value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANparameter_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANparameter_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RANparameter_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RANparameter_Item_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RANparameter_Item_H_ */
#include <asn_internal.h>
