/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#ifndef	_RIC_ControlStyle_Item_H_
#define	_RIC_ControlStyle_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RIC_ControlAction_Item;

/* RIC-ControlStyle-Item */
typedef struct RIC_ControlStyle_Item {
	RIC_Style_Type_t	 ric_ControlStyle_Type;
	RIC_Style_Name_t	 ric_ControlStyle_Name;
	struct RIC_ControlStyle_Item__ric_ControlAction_List {
		A_SEQUENCE_OF(struct RIC_ControlAction_Item) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_ControlAction_List;
	RIC_Format_Type_t	 ric_ControlHeaderFormat_Type;
	RIC_Format_Type_t	 ric_ControlMessageFormat_Type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RIC_ControlStyle_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RIC_ControlStyle_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_RIC_ControlStyle_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_RIC_ControlStyle_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RIC_ControlStyle_Item_H_ */
#include <asn_internal.h>
