/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "E2AP-IEs-v01.00.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_RICrequestID_H_
#define	_RICrequestID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RICrequestID */
typedef struct RICrequestID {
	long	 ricRequestorID;
	long	 ricInstanceID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RICrequestID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RICrequestID;
extern asn_SEQUENCE_specifics_t asn_SPC_RICrequestID_specs_1;
extern asn_TYPE_member_t asn_MBR_RICrequestID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RICrequestID_H_ */
#include <asn_internal.h>
