/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-RC"
 * 	found in "e2sm-kpm-rc.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example -D .`
 */

#include "ServingCellMeasurements.h"

#include "MeasResultServMOList.h"
#include "MeasResultPCell.h"
static asn_oer_constraints_t asn_OER_type_ServingCellMeasurements_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ServingCellMeasurements_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ServingCellMeasurements_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ServingCellMeasurements, choice.nr_measResultServingMOList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultServMOList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-measResultServingMOList"
		},
	{ ATF_POINTER, 0, offsetof(struct ServingCellMeasurements, choice.eutra_measResultPCell),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultPCell,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eutra-measResultPCell"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ServingCellMeasurements_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nr-measResultServingMOList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eutra-measResultPCell */
};
asn_CHOICE_specifics_t asn_SPC_ServingCellMeasurements_specs_1 = {
	sizeof(struct ServingCellMeasurements),
	offsetof(struct ServingCellMeasurements, _asn_ctx),
	offsetof(struct ServingCellMeasurements, present),
	sizeof(((struct ServingCellMeasurements *)0)->present),
	asn_MAP_ServingCellMeasurements_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ServingCellMeasurements = {
	"ServingCellMeasurements",
	"ServingCellMeasurements",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ServingCellMeasurements_constr_1, &asn_PER_type_ServingCellMeasurements_constr_1, CHOICE_constraint },
	asn_MBR_ServingCellMeasurements_1,
	2,	/* Elements count */
	&asn_SPC_ServingCellMeasurements_specs_1	/* Additional specs */
};

