/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v02.00.03.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example -D E2SM-KPM-v02.00.03`
 */

#ifndef	_SubscriptionID_H_
#define	_SubscriptionID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SubscriptionID */
typedef INTEGER_t	 SubscriptionID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SubscriptionID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SubscriptionID;
asn_struct_free_f SubscriptionID_free;
asn_struct_print_f SubscriptionID_print;
asn_constr_check_f SubscriptionID_constraint;
ber_type_decoder_f SubscriptionID_decode_ber;
der_type_encoder_f SubscriptionID_encode_der;
xer_type_decoder_f SubscriptionID_decode_xer;
xer_type_encoder_f SubscriptionID_encode_xer;
oer_type_decoder_f SubscriptionID_decode_oer;
oer_type_encoder_f SubscriptionID_encode_oer;
per_type_decoder_f SubscriptionID_decode_uper;
per_type_encoder_f SubscriptionID_encode_uper;
per_type_decoder_f SubscriptionID_decode_aper;
per_type_encoder_f SubscriptionID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriptionID_H_ */
#include <asn_internal.h>
