/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "E2SM-KPM-v02.00.03.asn"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER -no-gen-example -D E2SM-KPM-v02.00.03`
 */

#include "SubscriptionID.h"

int
SubscriptionID_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const INTEGER_t *st = (const INTEGER_t *)sptr;
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(asn_INTEGER2long(st, &value)) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value too large (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((value >= 1 && value <= 4294967296)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using INTEGER,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_SubscriptionID_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_SubscriptionID_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  32, -1,  1,  4294967296 }	/* (1..4294967296,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_SubscriptionID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_SubscriptionID = {
	"SubscriptionID",
	"SubscriptionID",
	&asn_OP_INTEGER,
	asn_DEF_SubscriptionID_tags_1,
	sizeof(asn_DEF_SubscriptionID_tags_1)
		/sizeof(asn_DEF_SubscriptionID_tags_1[0]), /* 1 */
	asn_DEF_SubscriptionID_tags_1,	/* Same as above */
	sizeof(asn_DEF_SubscriptionID_tags_1)
		/sizeof(asn_DEF_SubscriptionID_tags_1[0]), /* 1 */
	{ &asn_OER_type_SubscriptionID_constr_1, &asn_PER_type_SubscriptionID_constr_1, SubscriptionID_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

