/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxProtocolIEs (65535)
#define maxnoofErrors (256)
#define maxofRANfunctionID (256)
#define maxofRICactionID (16)
#define maxofRANParameters (255)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
