/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-HelloWorld-IEs"
 * 	found in "/home/sjana/ASN-Defns/e2sm-HelloWorld-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_HW_Header_H_
#define	_HW_Header_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* HW-Header */
typedef long	 HW_Header_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HW_Header;
asn_struct_free_f HW_Header_free;
asn_struct_print_f HW_Header_print;
asn_constr_check_f HW_Header_constraint;
ber_type_decoder_f HW_Header_decode_ber;
der_type_encoder_f HW_Header_encode_der;
xer_type_decoder_f HW_Header_decode_xer;
xer_type_encoder_f HW_Header_encode_xer;
per_type_decoder_f HW_Header_decode_uper;
per_type_encoder_f HW_Header_encode_uper;
per_type_decoder_f HW_Header_decode_aper;
per_type_encoder_f HW_Header_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _HW_Header_H_ */
#include <asn_internal.h>
