/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-HelloWorld-IEs"
 * 	found in "/home/sjana/ASN-Defns/e2sm-HelloWorld-v002.asn"
 * 	`asn1c -fno-include-deps -fcompound-names -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_RANparameter_Test_H_
#define	_RANparameter_Test_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RANparameter_Test {
	RANparameter_Test_equal	= 0,
	RANparameter_Test_greaterthan	= 1,
	RANparameter_Test_lessthan	= 2,
	RANparameter_Test_contains	= 3,
	RANparameter_Test_present	= 4
	/*
	 * Enumeration is extensible
	 */
} e_RANparameter_Test;

/* RANparameter-Test */
typedef long	 RANparameter_Test_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RANparameter_Test_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RANparameter_Test;
extern const asn_INTEGER_specifics_t asn_SPC_RANparameter_Test_specs_1;
asn_struct_free_f RANparameter_Test_free;
asn_struct_print_f RANparameter_Test_print;
asn_constr_check_f RANparameter_Test_constraint;
ber_type_decoder_f RANparameter_Test_decode_ber;
der_type_encoder_f RANparameter_Test_encode_der;
xer_type_decoder_f RANparameter_Test_decode_xer;
xer_type_encoder_f RANparameter_Test_encode_xer;
per_type_decoder_f RANparameter_Test_decode_uper;
per_type_encoder_f RANparameter_Test_encode_uper;
per_type_decoder_f RANparameter_Test_decode_aper;
per_type_encoder_f RANparameter_Test_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RANparameter_Test_H_ */
#include <asn_internal.h>
